"use client";
import { Kanit } from "next/font/google";
import "./globals.css";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import { Suspense, useEffect } from "react";
import Head from "next/head";
import { AlertDialogProvider } from "@/components/providers/alert-provider";
import { FullLoadingProvider } from "@/components/providers/full-loading-provider";
import {
  HelperProvider,
} from "@/components/providers/helper-provider";
import { AllCommunityModule, ModuleRegistry } from "ag-grid-community";

const kanit = Kanit({
  subsets: ["latin"],
  variable: "--font-kanit-sans",
  weight: "300",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    ModuleRegistry.registerModules([AllCommunityModule]);
  }, []);

  return (
    <Suspense fallback={<div></div>}>
      <html lang="en">
        <Head>
          <title>BEARHOUSE Fruad Detection</title>
          <meta name="description" content="Generated by IT" />
        </Head>
        <body className={`${kanit.variable} antialiased`}>
          <AlertDialogProvider>
            <FullLoadingProvider>
              <HelperProvider>{children}</HelperProvider>
            </FullLoadingProvider>
          </AlertDialogProvider>
        </body>
      </html>
    </Suspense>
  );
}
